#!/bin/bash
#$ -V

#PBS -S /bin/bash
#PBS -l nodes=1:ppn=16,mem=5g,walltime=12:00:00
#PBS -N freight_train
module use /software/spack/spack/share/spack/modules/linux-rocky8-sandybridge/
module load openfoam

cd /global-scratch/abrunelli/foamSimulation
chmod +x Allrun_cluster
#sort ${PBS_NODEFILE} | uniq -c | awk '{ printf("%s\n", $2); }' > /home/meccanica/abrunelli/mpd.nodes
time ./Allrun_cluster > /global-scratch/abrunelli/foamSimulation